### ISSUE TITLE
Notification message

### ISSUE THREAD

**Issue by Fridus** [ArtemGordinsky/Spotifree#62] opened 2015-08-19 14:25 UTC
Hi, 
`Music will be back in about 30000 seconds...` ? It's not too much ? :)

https://github.com/ArtemGordinsky/Spotifree/blob/8b19091f9c50cc6e619a1b650965e4e1d1606cfb/Spotifree/SpotifyController.m#L134

**Comment by apple-ihack-geek** [comment] 2015-08-31 14:09
I've seen similar as well.

**Comment by jostster** [comment] 2015-09-01 20:27
i've seen this as well. It seems that on these long ones it also pauses the song and you have to go in and hit next. My guess is Spotify is trying to prevent spotifree from working right.

**Comment by fabiosoft** [comment] 2015-09-11 13:43
I think the problem is the `long` casting on line [134](https://github.com/ArtemGordinsky/Spotifree/blob/8b19091f9c50cc6e619a1b650965e4e1d1606cfb/Spotifree/SpotifyController.m#L134)

![spotifree-notification](https://cloud.githubusercontent.com/assets/812037/9816137/5dc2d930-589b-11e5-9f85-ca8e3864add1.png)

**Comment by Fridus** [comment] 2015-11-06 10:56
@ArtemGordinsky ping

**Comment by robcalcroft** [comment] 2015-12-01 23:01
+1

**Comment by ArtemGordinsky** [comment] 2015-12-06 18:15
Fixed by #61.

**Closed by ArtemGordinsky** 2015-12-06 18:15 UTC

**Comment by robcalcroft** [comment] 2015-12-06 21:13
When is this gonna be in a release (if it's not already). Thanks

**Comment by ArtemGordinsky** [comment] 2015-12-07 03:46
It already is, I released 1.6.4 yesterday.

**Comment by robcalcroft** [comment] 2015-12-07 12:53
Ahh :+1: thanks
